name: demo-test-site
favicon: null
layout_spectrum: 0.34774984745308757
typography_spectrum: 0.061507654609158635
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.813023095484823
  lightness: 0.74585702852346
  saturation: 0.8921245511155576
  rhythmicContrast: 0.1353041515685618
purpose: []
