name: demo-test-site
favicon: null
layout_spectrum: 0.34775
typography_spectrum: 0.48007
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#252a2d'
    - '#665d54'
    - '#b8b6b7'
    - '#81776e'
    - '#d4d2d3'
  brandStrength: 0.6875
  lightness: 0.5625
  saturation: 0.5625
  rhythmicContrast: 0.1353041515685618
purpose: []
